//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace AppEntities.EntityClasses
{
    partial class DashboardReports
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "User", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in User")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String Username
        {
            get
            {
                return this.getString("Username");
            }
            set
            {
                this["Username"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Saved Report ID", Order = 1)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Saved Report ID")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual Int64 SavedReportID
        {
            get
            {
                return this.getLargeInteger("SavedReportID");
            }
            set
            {
                this["SavedReportID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "S No", Order = 2)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in S No")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual Int64 SNo
        {
            get
            {
                return this.getLargeInteger("SNo");
            }
            set
            {
                this["SNo"] = value;
            }
        }

    }
}
