//DO NOT MODIFY THIS FILE
//Instead, override the this[] indexer in your entity base class
using System;
using AppFramework.AppClasses;
namespace AppEntities.EntityClasses
{
    partial class InvestorsRegistration
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "InvestorID", Order = 0)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in InvestorID")]
        [System.ComponentModel.DataAnnotations.Editable(false, AllowInitialValue = false)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String InvestorID
        {
            get
            {
                return this.getString("InvestorID");
            }
            set
            {
                this["InvestorID"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "First Name", Order = 1)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in First Name")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String FirstName
        {
            get
            {
                return this.getString("FirstName");
            }
            set
            {
                this["FirstName"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Last Name", Order = 2)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Last Name")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String LastName
        {
            get
            {
                return this.getString("LastName");
            }
            set
            {
                this["LastName"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Middle Name", Order = 3)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String MiddleName
        {
            get
            {
                return this.getString("MiddleName");
            }
            set
            {
                this["MiddleName"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Email", Order = 4)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Email")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String Email
        {
            get
            {
                return this.getString("Email");
            }
            set
            {
                this["Email"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Primary Phone No", Order = 5)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Primary Phone No")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String PrimaryPhoneNo
        {
            get
            {
                return this.getString("PrimaryPhoneNo");
            }
            set
            {
                this["PrimaryPhoneNo"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Secondary Phone No", Order = 6)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String SecondaryPhoneNo
        {
            get
            {
                return this.getString("SecondaryPhoneNo");
            }
            set
            {
                this["SecondaryPhoneNo"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Address", Order = 7)]
        [System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.MultilineText)]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual String Address
        {
            get
            {
                return this.getString("Address");
            }
            set
            {
                this["Address"] = value;
            }
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "Means of Identification", Order = 8)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Please fill in Means of Identification")]
        [System.ComponentModel.DataAnnotations.Editable(true, AllowInitialValue = true)]
        [AppFramework.AppClasses.Autogenerated]
        public virtual byte[] MeansOfIdentification
        {
            get
            {
                return this.getBlob("MeansOfIdentification");
            }
            set
            {
                this["MeansOfIdentification"] = value;
            }
        }

    }
}
